name: Build and test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile
        run: javac -d out src/advent2016/*.java

      - name: Run tests
        run: java -cp out advent2016.Main test
